In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
multiply_arr_by_2 = arr * 2

In [6]:
multiply_arr_by_2

array([ 2,  4,  6,  8, 10])

In [7]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
second_row = arr[1]
second_row

array([4, 5, 6])

In [9]:
arr2d = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
arr2d.shape

(5, 5)

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
sum_row = arr.sum(axis=0)
sum_row

array([12, 15, 18])

In [13]:
sum_row1 = arr.sum(axis=1)
sum_row1

array([ 6, 15, 24])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
avg_num = arr.mean()
avg_num

5.0